### ISSUE TITLE
Python error when deploying

### ISSUE THREAD

**Issue by amaruki** [zeit/now#7678]
When i was deploying django app on vercel i got this error

> Error! Unable to find binary python3.8 for runtime python3.8
Error! Check your logs at https://komputama-qj1unu7v1-ngapa.vercel.app/_logs or run `vercel logs komputama-qj1unu7v1-ngapa.vercel.app`

And the log in the deployment status is

> [16:26:29.158] Retrieving list of deployment files...
[16:26:31.764] Downloading 1726 deployment files...
[16:26:38.432] Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
[16:26:38.619] Installing build runtime...
[16:26:42.087] Build runtime installed: 3.467s
[16:26:42.423] Looking up build cache...
[16:26:42.665] Build Cache not found
[16:26:42.856] Starting build
[16:26:42.861]       Build AMI version: Amazon Linux release 2 (Karoo)
[16:26:42.862]       Lambda runtime: python3.8
[16:26:42.862]       WSGI application: cores.wsgi.application
[16:26:42.862] ====> Selecting python version
[16:26:42.874] Error: Unable to find binary python3.8 for runtime python3.8
[16:26:42.874]     at Object.findPythonBinary (/vercel/7c1ee15da2687191/.build-utils/.builder/node_modules/@ardnt/vercel-python-wsgi/build-utils/python.js:23:9)
[16:26:42.874]     at Object.exports.build (/vercel/7c1ee15da2687191/.build-utils/.builder/node_modules/@ardnt/vercel-python-wsgi/index.js:34:34)
[16:26:42.874]     at async mut (/var/task/sandbox.js:197:17526)

This is my 'vercel.json'

> {
    "build": {
        "env": {
      
        }
    },
    "builds": [{
        "src": "cores/wsgi.py",
        "use": "@ardnt/vercel-python-wsgi",
        "config": { "maxLambdaSize": "15mb", "runtime": "python3.8" }
    }],
    "routes": [
        {
            "src": "/(.*)",
            "dest": "cores/wsgi.py"
        }
    ]
}

I got stuck with this, so anyone help me?

**Comment by is-it-ayush** [comment]
Instead of using ```"@ardnt/vercel-python-wsgi"```. Use ```"@natanffs/vercel-python-wsgi"```. Also Change: "runtime": "python3.9".
@ardnt hasn't yet updated to Python 3.9.

**Comment by QGB** [comment]
How to custom project start cmd (not "build.sh") in vercel.json?

**Comment by prabincankod** [comment]
Hey  @Ngapa 
use the official python runtime i.e.`@vercel/python`.
add `app = application` end of `cores/wsgi.py` because the official python wants to expose the your wsgi/asgi application via `app`'
[more details on python runtime ](https://vercel.com/docs/runtimes#advanced-usage/advanced-python-usage)

**Comment by andymckay** [comment]
Closing based on the last answer here, thanks everyone who helped. If you've got more questions then please contact support: https://vercel.com/help#issues thank you.

**Comment by ChristianSoledispa** [comment]
I had the same issue 2 days ago I got stuck

**Comment by prabincankod** [comment]
> I had the same issue 2 days ago I got stuck

is it resolved now ?

**Comment by ChristianSoledispa** [comment]
I tried to reconfigure my setting.py with static urls but when to run the command 'vercel dev' I had an error that I can't interprete it.
![image](https://github.com/vercel/vercel/assets/85883884/3cee828a-cf68-40a1-bff4-2d3ab7a59aa0)

**Comment by prajjwalz1** [comment]
![Screenshot 2023-08-26 233922](https://github.com/vercel/vercel/assets/34410880/a29b8491-8572-4013-be99-06fba171f996)
![Screenshot 2023-08-26 233553](https://github.com/vercel/vercel/assets/34410880/5b99b794-cf5c-43b0-9d4f-dc31ba53d337)
Help me fix my problem..i get this error after i try to deploy django apps on vercel.

**Comment by prabincankod** [comment]
> ![Screenshot 2023-08-26 233922](https://user-images.githubusercontent.com/34410880/263490423-a29b8491-8572-4013-be99-06fba171f996.jpg) ![Screenshot 2023-08-26 233553](https://user-images.githubusercontent.com/34410880/263490426-5b99b794-cf5c-43b0-9d4f-dc31ba53d337.jpg) Help me fix my problem..i get this error after i try to deploy django apps on vercel.

use the official runtime provided by vercel
and also export `app = get_wsgi_application()` in the wsgi file

**Comment by prabincankod** [comment]
@prajjwalz1 plss stop playing around the repo i fixed itl
[in my fork](https://github.com/prabincankod/carringmanagementvercel)

**Comment by prajjwalz1** [comment]
![Screenshot 2023-08-27 022601](https://github.com/vercel/vercel/assets/34410880/bf667ab7-79bf-47e8-83e1-4a03799f631d)
Got this error after i added postgresql database.

**Comment by sarveshver** [comment]
> ![Screenshot 2023-08-27 022601](https://private-user-images.githubusercontent.com/34410880/263496451-bf667ab7-79bf-47e8-83e1-4a03799f631d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDcxNTIsIm5iZiI6MTcwMTQ0Njg1MiwicGF0aCI6Ii8zNDQxMDg4MC8yNjM0OTY0NTEtYmY2NjdhYjctNzliZi00N2U4LTgzZTEtNGEwMzc5OWY2MzFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE2MDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NWMwMjYxNjg2NDA2NDMxMTBhOWQ1YWQ0YjlhMDZhYzY5OTUxZDhlZTc4YzY4ZTkzZWRlNDQ1NDliNzAxMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1JBlRfPw5Lq125zq78ED6KuvOY_1bj8fwEMCZD5PM6U) Got this error after i added postgresql database.

just try to install  pip install psycopg2-binary then commit the change it will get clear

**Comment by alby-francis** [comment]
![image](https://github.com/vercel/vercel/assets/67657752/1bde3aa0-f749-4a0e-a333-8ea88dc8cbe7)
I also faced this same error and also i followed step provided by @prabincankod of adding app = application and setting python version to 3.9 , but still getting this issue. Also i am using the official @vercel/python

Edit 1:
This is the error
WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings

17:06:07.186 | Error: Unable to find any supported Python versions.
17:06:07.187 | Learn More: http://vercel.link/python-version

Edit 2:
Also I am using python 3.9.11 for the project

**Comment by shafschwd** [comment]
> ![image](https://private-user-images.githubusercontent.com/67657752/316843047-1bde3aa0-f749-4a0e-a333-8ea88dc8cbe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTU4MTAsIm5iZiI6MTcxMTQ1NTUxMCwicGF0aCI6Ii82NzY1Nzc1Mi8zMTY4NDMwNDctMWJkZTNhYTAtZjc0OS00YTBlLWEzMzMtOGVhODhkYzhjYmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEyMTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiY2Y4NmQ2MmFhOTk3MWVhMzJkZTFlNjcyNTgzNzE2ZmUyYTI2MDMwMjQzYWNhNDI3N2JmNzcyMDI0Yjg2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8wxmdlGSdw1cTjmkxFlrMc6POOD2Jsod-g7ETwZ64C4) I also faced this same error and also i followed step provided by @prabincankod of adding app = application and setting python version to 3.9 , but still getting this issue. Also i am using the official @vercel/python
> 
> Edit 1: This is the error WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
> 
> 17:06:07.186 | Error: Unable to find any supported Python versions. 17:06:07.187 | Learn More: http://vercel.link/python-version
> 
> Edit 2: Also I am using python 3.9.11 for the project

same error

**Comment by nonepork** [comment]
> > ![image](https://private-user-images.githubusercontent.com/67657752/316843047-1bde3aa0-f749-4a0e-a333-8ea88dc8cbe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTU4MTAsIm5iZiI6MTcxMTQ1NTUxMCwicGF0aCI6Ii82NzY1Nzc1Mi8zMTY4NDMwNDctMWJkZTNhYTAtZjc0OS00YTBlLWEzMzMtOGVhODhkYzhjYmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEyMTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiY2Y4NmQ2MmFhOTk3MWVhMzJkZTFlNjcyNTgzNzE2ZmUyYTI2MDMwMjQzYWNhNDI3N2JmNzcyMDI0Yjg2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8wxmdlGSdw1cTjmkxFlrMc6POOD2Jsod-g7ETwZ64C4) I also faced this same error and also i followed step provided by @prabincankod of adding app = application and setting python version to 3.9 , but still getting this issue. Also i am using the official @vercel/python
> > Edit 1: This is the error WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
> > 17:06:07.186 | Error: Unable to find any supported Python versions. 17:06:07.187 | Learn More: http://vercel.link/python-version
> > Edit 2: Also I am using python 3.9.11 for the project
> 
> same error

Change node.js version to 18.x in project settings works for me.

**Comment by alby-francis** [comment]
Yeah, that worked me as well

**Comment by alby-francis** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/67657752/316843047-1bde3aa0-f749-4a0e-a333-8ea88dc8cbe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTU4MTAsIm5iZiI6MTcxMTQ1NTUxMCwicGF0aCI6Ii82NzY1Nzc1Mi8zMTY4NDMwNDctMWJkZTNhYTAtZjc0OS00YTBlLWEzMzMtOGVhODhkYzhjYmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEyMTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiY2Y4NmQ2MmFhOTk3MWVhMzJkZTFlNjcyNTgzNzE2ZmUyYTI2MDMwMjQzYWNhNDI3N2JmNzcyMDI0Yjg2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8wxmdlGSdw1cTjmkxFlrMc6POOD2Jsod-g7ETwZ64C4) I also faced this same error and also i followed step provided by @prabincankod of adding app = application and setting python version to 3.9 , but still getting this issue. Also i am using the official @vercel/python
> > > Edit 1: This is the error WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
> > > 17:06:07.186 | Error: Unable to find any supported Python versions. 17:06:07.187 | Learn More: http://vercel.link/python-version
> > > Edit 2: Also I am using python 3.9.11 for the project
> > 
> > same error
> 
> Change node.js version to 18.x in project settings works for me.

Yeah, that worked for me as well

**Comment by draew6** [comment]
> Change node.js version to 18.x in project settings works for me.

thank you, that worked! no chance for me to come up with this :D

**Comment by MayankSuthar1** [comment]
how Change node.js version to 18.x in project settings i am getting the same error but i dont know how to change the version please help me
 thank you in advance

**Comment by draew6** [comment]
@MayankSuthar1 go to vercel.com, pick a project and then go to Settings > General -> Node.js Version. Pick 18.x

**Comment by Mayankkumar21** [comment]
Facing a similar issue is it possible to change node version while deploying for the first time?

**Comment by prajjwalz1** [comment]
Guys for python django I dont recommend using vercel for deployment but if you just want to test it.please check this two screenshots that may help you to succesfully deploy. 


![Screenshot 2024-04-06 114608](https://github.com/vercel/vercel/assets/34410880/208cf548-0a4a-46d4-a009-ca51a40d855a)
![Screenshot 2024-04-06 114552](https://github.com/vercel/vercel/assets/34410880/f96228a4-2e20-47d3-a456-44e61b886297)

**Comment by LuizMateuss** [comment]
I solved this problem by following these steps:
https://stackoverflow.com/questions/76041512/error-while-installing-mysqlclient-on-vercel-for-django-app
