### ISSUE TITLE
Cannot find module in the workspace?

### ISSUE THREAD

**Issue by Blatty** [zeit/now#8063]
### What version of Turborepo are you using?

1.3.1

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

First of all, thank you for this amazing project. We've been enjoying using turborepo for the past 6 months and we love it so far!

I'm not sure if this is a bug report, but after digging into the issues and discussions, I couldn't find anything near the problem we are currently facing and after triple checking the docs and a few hours of debug, we decided to open an issue ✋ 

We're currently using Vercel and deploying an api using Fastify, we are using a similar setup than [this one](https://vercel.com/guides/using-express-with-vercel), we named it `@acme/api` for the reproduction.

When trying to import another package (`@acme/utils`) into the `@acme/api` project, the project would not build:

```NowBuildError: src/app.ts(2,23): error TS2307: Cannot find module '@acme/utils' or its corresponding type declarations.```

I made the logs public, if it helps: https://turbo-vercel-repro-h8fvyigkv-blatty.vercel.app/_logs

And here's our `turbo.json`:

```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**", "build/**", ".next/**", "public/**"]
    },
    "@acme/api#build": {
      "dependsOn": ["^build", "@acme/utils#build"],
      "outputs": ["dist/**", "build/**"]
    },
    "@acme/utils#build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**"]
    },
    "start": {
      "cache": false
    },
    "dev": {
      "cache": false
    }
  },
  "baseBranch": "origin/main",
  "globalDependencies": ["$GITHUB_TOKEN", "tsconfig.json"]
}
```

### Expected Behavior

Expected `@acme/utils` to be included in `@acme/api`

### To Reproduce

1. Clone the reproduction repo: https://github.com/Blatty/turbo-vercel-repro
2. Deploy to vercel, set the root directory to `apps/api`
3. Set the build command to `cd ../../ && npx turbo run build --filter=@acme/api`

We also tried with  `--no-cache` & `--force`, `yarn install --cwd ../..` as the "install command" to trigger the `postinstall` but without success 😞

**Comment by nathanhammond** [comment]
Okay, so you're running into a weird edge case at the interactions between Yarn and Vercel. For better or worse, this has nothing to do with Turborepo.

What's going on:
1. Yarn `install` must be run at the root of the workspace in order to successfully link everything.
2. [If you set the Root Directory for Vercel that changes the installation behavior](https://vercel.com/docs/concepts/deployments/build-step#root-directory) so it's not surprising that you can't use the installation tricks you're reaching for.

I'll see if I can find a better place to get this addressed.

**Comment by nathanhammond** [comment]
I suspect that the behavior is this:
1. A serverless function is deployed as part of a monorepo.
2. The root directory is set to be the serverless function.

Bug:
Upon arrival in the server environment, the dependency (which was previously symlinked within the repo by the workspace manager, e.g. Yarn) is no longer available.

**Comment by Blatty** [comment]
Thank you for looking into this @nathanhammond and sorry if I misplaced the issue in the first place.

You're right, when the build cache hits the symlinked dependency in unavailable, when using `VERCEL_DEBUG=1` I can clearly see:

```
node_modules/@acme/utils is a symlink and it's children will be excluded from cache
```

It looks like Vercel does not support Symlinks, according to this discussion: https://github.com/vercel/vercel/discussions/5347

Other related discussion:
https://github.com/vercel/vercel/discussions/4352

**Comment by Blatty** [comment]
Although, if Vercel doesn't support symlinks and the Git <> Vercel integration [doesn't have an option to skip the build](https://github.com/vercel/vercel/discussions/8057#discussioncomment-3057196) cache, what's the best alternative there?

**Comment by nathanhammond** [comment]
@Blatty No worries! The right people saw it. 👍 I appreciate the time you put into making this easy to address on our side.

**Comment by Blatty** [comment]
Quick update, we found an alternative by moving to the legacy `builds` & `routes` path:

```json
{
  "version": 2,
  "regions": ["syd1"],
  "builds": [
    {
      "src": "api/index.ts",
      "use": "@vercel/node",
      "config": {
        "helpers": false,
        "maxDuration": 60
      }
    }
  ],
  "routes": [
    {
      "src": "/.*",
      "dest": "api/index.ts"
    }
  ]
}
```

Pros:
It works!

Cons:
It's legacy? 🤷
It doesn't respect the installation & build steps so we had to adjust the postinstall to build the `utils` package respectively in `apps/api/package.json`:

```json

{ 
  "scripts" : {
    "postinstall": "ROOTPATH=$(echo $PWD | sed -e 's/apps\\/api//g') && yarn --cwd $ROOTPATH postinstall"
  }
}

```

**Comment by nathanhammond** [comment]
@styfle I believe that this is the minimal reproduction: https://github.com/nathanhammond/workspace-symlink-issue

It fails differently, but I'm ~sure that it's the same root cause. (Early vs. late failure.)

Vercel configuration:
- build: `cd ../.. && yarn build`
- install `cd ../.. && yarn`
- root directory: `apps/api`

**Comment by styfle** [comment]
@nathanhammond Thanks for the repo!

The reason why it sometimes works and sometimes doesn't is because the `builds` order is not guaranteed.

The Build Command of `cd ../.. && yarn build` is run by `@vercel/static-build` and the Serverless Functions in the `api` directory are created by `@vercel/node`.

I think we can change this behavior such that "frontend" builds (in this case `@vercel/static-build`) execute before the "backend" builds (in this case `@vercel/node`). We also can make sure each build in a deployment shares the same filesystem so it works the same locally as it does once deployed.

This should be fixed in #8144

**Comment by Blatty** [comment]
Thank you so much @styfle & @nathanhammond 🙏

**Comment by Blatty** [comment]
Are the changes on Vercel yet?

It's still missing the runtime dependency for me: https://vercel.com/blatty/workspace-symlink-issue/7BpyXGPbPZ92WCmmwzoEEZRtNgqE

**Comment by styfle** [comment]
This change was only applied to `vercel build`. Try with `ENABLE_VC_BUILD=1` environment variable and deploy again.

**Comment by bbozzay** [comment]
@styfle I'm still running into the exact issue mentioned by @Blatty even when using `ENABLE_VC_BUILD`. The only difference is that I'm using pnpm.

**Comment by styfle** [comment]
Please create a new issue with the code to reproduce the issue.

Or file a [support ticket](https://vercel.com/help#:~:text=work%20on%20Vercel-,Reach%20out,-on%20our%20official) and our team will take a look, thanks!
